CREATE TABLE IF NOT EXISTS public.chat_handoffs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL REFERENCES public.chat_threads(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  reason TEXT,
  admin_reply TEXT,
  replied_by_user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  replied_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_chat_handoffs_status_created_at
  ON public.chat_handoffs (status, created_at);

CREATE INDEX IF NOT EXISTS idx_chat_handoffs_user_created_at
  ON public.chat_handoffs (user_id, created_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_chat_handoffs_pending_thread
  ON public.chat_handoffs (thread_id)
  WHERE status = 'pending';
